# Generated by Django 4.0.1 on 2023-07-01 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(blank=True, max_length=30, verbose_name='部門ID')),
                ('department_name', models.CharField(blank=True, max_length=30, verbose_name='部門名稱')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='標題')),
                ('type', models.CharField(choices=[('1', '財務部'), ('2', '員工相關')], max_length=1)),
                ('content', models.TextField(blank=True, null=True, verbose_name='編輯器內文')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '最新消息',
                'verbose_name_plural': '最新消息',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=30, verbose_name='員工ID')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='職位')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('departments', models.ManyToManyField(blank=True, related_name='employees', to='Backend.Department', verbose_name='部門')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
