# Generated by Django 4.2.2 on 2023-07-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_department_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='parent_department',
        ),
    ]
