# Generated by Django 4.0.1 on 2023-07-02 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_department_id_department_parent_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(max_length=30, verbose_name='報價單號')),
                ('projecet_id', models.CharField(max_length=30, verbose_name='工派單編號')),
                ('project_name', models.CharField(max_length=30, verbose_name='工程名稱')),
                ('c_a', models.CharField(max_length=50, verbose_name='母案編號')),
                ('attendance_date', models.DateField(blank=True, null=True, verbose_name='出勤日期')),
                ('vehicle', models.CharField(max_length=30, verbose_name='使用車輛')),
                ('location', models.CharField(max_length=30, verbose_name='工作地點')),
                ('project_type', models.CharField(max_length=30, verbose_name='工作類型')),
                ('remark', models.CharField(max_length=30, verbose_name='備註')),
                ('support', models.CharField(max_length=30, verbose_name='支援人力')),
                ('attachment', models.FileField(upload_to='project-attachment', verbose_name='工確單附件')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('lead_employee', models.ManyToManyField(related_name='projects_lead_employee', to='Backend.Employee', verbose_name='帶班人員')),
                ('work_employee', models.ManyToManyField(related_name='projects_work_employee', to='Backend.Employee', verbose_name='工作人員')),
            ],
            options={
                'verbose_name': '工作派任計畫',
                'verbose_name_plural': '工作派任計畫',
            },
        ),
    ]
