# Generated by Django 4.0.1 on 2023-07-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lead_employee',
        ),
        migrations.AddField(
            model_name='project',
            name='lead_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_lead_employee', to='Backend.employee', verbose_name='帶班人員'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='work_employee',
        ),
        migrations.AddField(
            model_name='project',
            name='work_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_work_employee', to='Backend.employee', verbose_name='工作人員'),
        ),
    ]
