# Generated by Django 4.2.2 on 2023-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_clock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='date',
        ),
    ]
