# Generated by Django 4.0.1 on 2023-07-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_remove_clock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份證字號'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手機號碼'),
        ),
        migrations.AddField(
            model_name='employee',
            name='seniority',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='目前年資'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='到職日期'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='Backend.Department', verbose_name='部門名稱'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='職稱'),
        ),
    ]
