# Generated by Django 4.0.1 on 2023-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '員工', 'verbose_name_plural': '員工'},
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齡'),
        ),
    ]
