# Generated by Django 4.0.1 on 2023-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_project_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '獎懲規範'), ('2', '系統相關'), ('3', '出勤與薪資相關'), ('4', '車輛相關'), ('5', '津貼相關'), ('6', '異常報告相關')], max_length=1, null=True, verbose_name='公告類別'),
        ),
        migrations.AddField(
            model_name='news',
            name='level',
            field=models.CharField(blank=True, choices=[('H', '高'), ('M', '中'), ('L', '低')], max_length=1, null=True, verbose_name='重要性'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='公告標題'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '獎懲規範'), ('2', '系統相關'), ('3', '出勤與薪資相關'), ('4', '車輛相關'), ('5', '津貼相關'), ('6', '異常報告相關')], max_length=1, null=True, verbose_name='類別'),
        ),
    ]
