# Generated by Django 4.0.1 on 2023-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_department_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='部門名稱'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='部門編號'),
        ),
    ]
