# Generated by Django 4.0.1 on 2023-07-06 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projecet_id',
            field=models.CharField(max_length=50, verbose_name='工派單編號'),
        ),
        migrations.CreateModel(
            name='Project_Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='報價單號')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='工程名稱')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='訂單編號')),
                ('c_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='母案編號')),
                ('client', models.CharField(blank=True, max_length=20, null=True, verbose_name='客戶簡稱')),
                ('requisition', models.CharField(blank=True, max_length=50, null=True, verbose_name='請購單位')),
                ('turnover', models.CharField(blank=True, max_length=10, null=True, verbose_name='成交金額')),
                ('is_completed', models.BooleanField(verbose_name='完工狀態')),
                ('completion_report_date', models.DateField(blank=True, null=True, verbose_name='完工回報日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('reassignment_attachment', models.FileField(blank=True, null=True, upload_to='project_confirmation_reassignment_attachment', verbose_name='完工重派附件')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('completion_report_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_confirmation_report_employee', to='Backend.employee', verbose_name='完工回報人')),
            ],
            options={
                'verbose_name': '工作派任計畫',
                'verbose_name_plural': '工作派任計畫',
            },
        ),
    ]
