# Generated by Django 4.0.1 on 2023-07-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_alter_project_projecet_id_project_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_confirmation',
            options={'verbose_name': '工程確認單', 'verbose_name_plural': '工程確認單'},
        ),
    ]
