# Generated by Django 4.2.3 on 2023-07-10 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='clock',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
