# Generated by Django 4.0.1 on 2023-07-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_alter_clock_employee_id'),
        ('Backend', '0022_clock_created_date_clock_update_date'),
    ]

    operations = [
    ]
