# Generated by Django 4.2.3 on 2023-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_merge_20230710_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.AlterField(
            model_name='clock',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.employee'),
        ),
    ]
