# Generated by Django 4.0.1 on 2023-07-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_alter_project_confirmation_quotation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='projecet_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工派單編號'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='project_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工程名稱'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='quotation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='報價單號'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='support',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支援人力'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='vehicle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='使用車輛'),
        ),
    ]
