# Generated by Django 4.0.1 on 2023-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_alter_project_job_assign_projecet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='c_a',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='母案編號'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工作地點'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='project_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工作類型'),
        ),
    ]
