# Generated by Django 4.0.1 on 2023-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_remove_project_job_assign_lead_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_confirmation',
            name='completion_report_employee',
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(related_name='projects_confirmation_report_employee', to='Backend.Employee', verbose_name='完工回報人'),
        ),
    ]
