# Generated by Django 4.0.1 on 2023-07-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0031_remove_project_confirmation_completion_report_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '中介資料庫',
                'verbose_name_plural': '中介資料庫',
            },
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(related_name='projects_confirmation_report_employee', through='Backend.Data_Management', to='Backend.Employee', verbose_name='完工回報人'),
        ),
        migrations.AddField(
            model_name='data_management',
            name='project_confirmation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.project_confirmation'),
        ),
    ]
