# Generated by Django 4.0.1 on 2023-07-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0032_data_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Backend.department', verbose_name='部門名稱'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(related_name='projects_confirmation_report_employee', to='Backend.Employee', verbose_name='完工回報人'),
        ),
        migrations.DeleteModel(
            name='Data_Management',
        ),
    ]
