# Generated by Django 4.0.1 on 2023-07-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_alter_project_confirmation_completion_report_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='abnormal_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='異常狀態'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='abnormal_condition_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='狀態說明'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='abnormal_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='異常說明'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='abnormal_img',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_abnormal_img/', verbose_name='異常照片'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='accruing_amounts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='維修累計金額'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='採購人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='check_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='校驗報告編碼'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='check_remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='校驗註記'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost_including_tax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='購入成本(含稅)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='custodian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保管人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='購入日期'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='detailed_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='盤點'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='發票號碼'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='校驗類別'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='latest_check_date',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='最近一次校驗日'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='維修狀態'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturing_numbe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='製造序號'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='normal_or_abnormal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='正常/異常'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='number_of_repairs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='維修累計次數'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='produced_stickers',
            field=models.BooleanField(blank=True, null=True, verbose_name='需補產編貼紙'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='送修日'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='repair_finished_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='庫存地點'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='供應商'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='transmitter',
            field=models.CharField(blank=True, choices=[('1', '大'), ('2', '小')], max_length=1, null=True, verbose_name='發報器大小'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保固期'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保固期間'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_confirmation_report_employee', to='Backend.Employee', verbose_name='完工回報人'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project-attachment/', verbose_name='工確單附件'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='lead_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_lead_employee', to='Backend.Employee', verbose_name='帶班人員'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='work_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_work_employee', to='Backend.Employee', verbose_name='工作人員'),
        ),
    ]
