# Generated by Django 4.0.1 on 2023-07-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_employee_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
    ]
