# Generated by Django 4.0.1 on 2023-07-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_equipment_abnormal_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='author',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='author',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='author',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee', verbose_name='建立人'),
        ),
    ]
