# Generated by Django 4.0.1 on 2023-07-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_remove_employee_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Confirmation_Employee_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(related_name='projects_confirmation_report_employee', through='Backend.Project_Confirmation_Employee_Management', to='Backend.Employee', verbose_name='完工回報人'),
        ),
        migrations.AddField(
            model_name='project_confirmation_employee_management',
            name='project_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.project_confirmation'),
        ),
    ]
