# Generated by Django 4.2.3 on 2023-07-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_equipment_author_project_confirmation_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_job_assign',
            name='c_a',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='projecet_id',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='quotation_id',
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='project_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='Backend.project_confirmation', verbose_name='工程名稱'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='完工狀態'),
        ),
    ]
