# Generated by Django 4.0.1 on 2023-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_project_confirmation_employee_management_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Confirmation_Employee_Management',
            new_name='ProjectConfirmationEmployeeManagement',
        ),
    ]
