# Generated by Django 4.0.1 on 2023-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0036_rename_project_confirmation_employee_management_projectconfirmationemployeemanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_confirmation',
            name='completion_report_employee',
            field=models.ManyToManyField(related_name='projects_confirmation_report_employee', to='Backend.Employee', verbose_name='完工回報人'),
        ),
        migrations.DeleteModel(
            name='ProjectConfirmationEmployeeManagement',
        ),
    ]
