# Generated by Django 4.2.3 on 2023-07-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0036_remove_project_job_assign_c_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='project_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='Backend.project_confirmation', verbose_name='工程確認單'),
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='support',
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='projects_support_employee', to='Backend.employee', verbose_name='支援人力'),
        ),
    ]
