# Generated by Django 4.0.1 on 2023-07-17 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0037_alter_project_confirmation_completion_report_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='資產標籤')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='序號')),
                ('equipment_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='資產種類別')),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='中類')),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('product_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='廠牌/型號')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '固定資產管理',
                'verbose_name_plural': '固定資產管理',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '公告'), ('2', '文管')], max_length=1, null=True, verbose_name='類別'),
        ),
    ]
