# Generated by Django 4.2.3 on 2023-07-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0037_alter_project_job_assign_project_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_job_assign',
            old_name='support',
            new_name='support_employee',
        ),
    ]
