# Generated by Django 4.0.1 on 2023-07-22 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0038_rename_support_project_job_assign_support_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='support_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_support_employee', to='Backend.Employee', verbose_name='支援人力'),
        ),
        migrations.CreateModel(
            name='Project_Employee_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_date', models.DateField(blank=True, null=True, verbose_name='施工日期')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='完工狀態')),
                ('construction_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='施工地點')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用車輛')),
                ('manuscript_return_date', models.DateField(blank=True, null=True, verbose_name='手稿預計回傳日')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project-attachment/', verbose_name='工確單附件')),
                ('enterprise_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='業主簽名')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('author', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.employee', verbose_name='建立人')),
                ('lead_employee', models.ManyToManyField(blank=True, related_name='employee_assign_lead_employee', to='Backend.Employee', verbose_name='帶班主管')),
                ('project_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_employee_assign', to='Backend.project_confirmation', verbose_name='工程確認單')),
                ('work_employee', models.ManyToManyField(blank=True, related_name='employee_assign_work_employee', to='Backend.Employee', verbose_name='檢測人員')),
            ],
            options={
                'verbose_name': '派工單',
                'verbose_name_plural': '派工單',
            },
        ),
    ]
