# Generated by Django 4.0.1 on 2023-07-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0040_remove_project_employee_assign_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_confirmation',
            options={'ordering': ['-id'], 'verbose_name': '工程確認單', 'verbose_name_plural': '工程確認單'},
        ),
        migrations.AlterModelOptions(
            name='project_employee_assign',
            options={'ordering': ['-id'], 'verbose_name': '派工單', 'verbose_name_plural': '派工單'},
        ),
        migrations.AlterModelOptions(
            name='project_job_assign',
            options={'ordering': ['-id'], 'verbose_name': '工作派任計畫', 'verbose_name_plural': '工作派任計畫'},
        ),
        migrations.RenameField(
            model_name='project_employee_assign',
            old_name='work_employee',
            new_name='inspector',
        ),
    ]
