# Generated by Django 4.0.1 on 2023-07-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0042_employee_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='enterprise_signature',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='業主簽名'),
        ),
    ]
