# Generated by Django 4.2.3 on 2023-07-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0045_news_modified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='editor_content',
        ),
    ]
