# Generated by Django 4.2.3 on 2023-07-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0046_rename_content_news_editor_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
    ]
