# Generated by Django 3.2.20 on 2023-07-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0048_alter_news_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
    ]
