# Generated by Django 3.2.20 on 2023-07-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0049_alter_news_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_confirmation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='author',
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
    ]
