# Generated by Django 3.2.20 on 2023-07-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0054_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='attendance_date',
            field=models.JSONField(blank=True, null=True, verbose_name='出勤日期'),
        ),
    ]
