# Generated by Django 3.2.20 on 2023-07-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0057_alter_project_job_assign_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news_attachment', verbose_name='公告附件'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='attendance_date',
            field=models.JSONField(blank=True, null=True, verbose_name='出勤日期'),
        ),
    ]
