# Generated by Django 3.2.20 on 2023-07-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0058_auto_20230728_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='project_confirmation',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='support_employee',
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='project_job_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employee_assign', to='Backend.project_job_assign', verbose_name='工程確認單'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.employee'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='project_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Backend.project_confirmation', verbose_name='工程確認單'),
        ),
    ]
