# Generated by Django 3.2.20 on 2023-08-01 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0059_auto_20230731_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.employee'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('vehicle_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='車牌號碼')),
                ('vehicle_type', models.CharField(blank=True, choices=[('R', '一般用車'), ('M', '經理配車')], max_length=1, null=True, verbose_name='車輛類型')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '車輛',
                'verbose_name_plural': '車輛',
            },
        ),
    ]
