# Generated by Django 3.2.20 on 2023-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0065_auto_20230804_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='員工名稱'),
        ),
    ]
