# Generated by Django 3.2.20 on 2023-08-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0066_alter_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_employee_assign',
            name='project_job_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employee_assign', to='Backend.project_job_assign', verbose_name='工作派任計畫'),
        ),
    ]
