# Generated by Django 3.2.20 on 2023-08-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0067_alter_project_employee_assign_project_job_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock', to='Backend.employee'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='carry_equipments',
            field=models.ManyToManyField(blank=True, related_name='carry_project', to='Backend.Equipment', verbose_name='攜帶資產'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='enterprise_signature',
            field=models.ImageField(blank=True, null=True, upload_to='Employee_Assign_Signature', verbose_name='業主簽名'),
        ),
    ]
