# Generated by Django 3.2.20 on 2023-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0070_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='出勤日期'),
        ),
    ]
