# Generated by Django 3.2.20 on 2023-08-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0071_alter_project_job_assign_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='buy_img',
            field=models.ImageField(blank=True, null=True, upload_to='buy_img/', verbose_name='買進照片'),
        ),
    ]
