# Generated by Django 3.2.20 on 2023-08-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0072_equipment_buy_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='vehicle',
        ),
    ]
