# Generated by Django 3.2.20 on 2023-08-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0073_remove_project_employee_assign_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_TargetDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='表單名稱')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.department')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('completed', '完成'), ('in_progress', '進行中'), ('rejected', '駁回')], default='in_progress', max_length=20)),
                ('current_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_approvals', to='Backend.department')),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Backend.approval_targetdepartment')),
            ],
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='Approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_logs', to='Backend.approvalmodel'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
