# Generated by Django 3.2.20 on 2023-08-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0074_auto_20230815_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_targetdepartment',
            options={'verbose_name': '簽核流程管理', 'verbose_name_plural': '簽核流程管理'},
        ),
        migrations.AlterModelOptions(
            name='approvalmodel',
            options={'verbose_name': '簽核狀態', 'verbose_name_plural': '簽核狀態'},
        ),
        migrations.AlterField(
            model_name='approval_targetdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.department', verbose_name='簽到哪個部門'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='Approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_confirmation_Approval', to='Backend.approvalmodel'),
        ),
    ]
