# Generated by Django 3.2.20 on 2023-08-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0075_auto_20230815_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_confirmation',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_confirmation_Approval', to='Backend.approvalmodel'),
        ),
    ]
