# Generated by Django 3.2.20 on 2023-08-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0076_alter_project_confirmation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_job_assign',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_Job_Assign_Approval', to='Backend.approvalmodel'),
        ),
    ]
