# Generated by Django 3.2.20 on 2023-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0078_project_employee_assign_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='employee',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
    ]
