# Generated by Django 3.2.20 on 2023-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0079_auto_20230816_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='department',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
    ]
