# Generated by Django 3.2.20 on 2023-08-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0080_auto_20230816_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval_targetdepartment',
            name='belong_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_department', to='Backend.department', verbose_name='屬於哪部門的簽核'),
        ),
        migrations.AlterField(
            model_name='approval_targetdepartment',
            name='name',
            field=models.CharField(choices=[('工程確認單', '工程確認單'), ('工程派任計畫單', '工程派任計畫單'), ('派工單', '派工單')], max_length=20, verbose_name='表單名稱'),
        ),
    ]
