# Generated by Django 3.2.20 on 2023-08-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0081_auto_20230817_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
        migrations.RemoveField(
            model_name='department',
            name='author',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='author',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_confirmation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='author',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='New_author', to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Confirmation_author', to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Employee_Assign_author', to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='project_job_assign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Job_Assign_author', to='Backend.employee'),
        ),
    ]
