# Generated by Django 3.2.20 on 2023-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0082_auto_20230817_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='belong_to_company',
            field=models.CharField(blank=True, choices=[('艾力克電機', '艾力克電機'), ('維景', '維景')], max_length=20, null=True, verbose_name='所屬公司'),
        ),
    ]
