# Generated by Django 3.2.20 on 2023-08-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0083_department_belong_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/users/')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='userfile', to='Backend.UploadedFile'),
        ),
    ]
