# Generated by Django 3.2.20 on 2023-08-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0084_auto_20230818_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, related_name='userfile', to='Backend.UploadedFile'),
        ),
    ]
