# Generated by Django 3.2.20 on 2023-08-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0086_auto_20230819_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': '檔案上傳管理', 'verbose_name_plural': '檔案上傳管理'},
        ),
        migrations.RemoveField(
            model_name='project_job_assign',
            name='job_assign_id',
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='current_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_approvals', to='Backend.department', verbose_name='待簽核'),
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='target_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Backend.approval_targetdepartment', verbose_name='依附簽核'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Confirmation_author', to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Employee_Assign_author', to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Job_Assign_author', to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='employee_profile/users/'),
        ),
    ]
