# Generated by Django 3.2.20 on 2023-08-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0087_auto_20230821_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_confirmation',
            name='project_confirmation_id',
        ),
    ]
