# Generated by Django 3.2.20 on 2023-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0089_auto_20230822_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_item',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='單價'),
        ),
    ]
