# Generated by Django 3.2.20 on 2023-08-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0090_alter_work_item_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('tax_id', models.CharField(max_length=20, verbose_name='統一編號')),
                ('contact_person', models.CharField(max_length=50, verbose_name='聯絡人')),
                ('address', models.TextField(verbose_name='地址')),
                ('tel', models.CharField(max_length=20, verbose_name='電話')),
                ('mobile', models.CharField(max_length=20, verbose_name='手機')),
                ('fax', models.CharField(max_length=20, verbose_name='傳真')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('project_name', models.CharField(max_length=100, verbose_name='專案名稱')),
                ('quote_validity_period', models.IntegerField(verbose_name='報價單有效期')),
                ('business_tel', models.CharField(max_length=20, verbose_name='業務電話')),
                ('business_assistant', models.CharField(max_length=50, verbose_name='業務助理')),
                ('work_item', models.ManyToManyField(blank=True, related_name='quotations', to='Backend.Work_Item')),
            ],
            options={
                'verbose_name': '報價單',
                'verbose_name_plural': '報價單',
            },
        ),
    ]
