# Generated by Django 3.2.20 on 2023-08-23 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0091_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
