# Generated by Django 3.2.20 on 2023-08-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0093_auto_20230823_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_item',
            name='work_item_id',
        ),
    ]
