# Generated by Django 3.2.20 on 2023-08-23 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0094_remove_work_item_work_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('date_of_overtime', models.DateField(blank=True, null=True, verbose_name='加班日期')),
                ('type_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班類別')),
                ('start_time_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班起始時間')),
                ('end_time_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班結束時間')),
                ('overtime_hours', models.IntegerField(blank=True, null=True, verbose_name='申請時數')),
                ('carry_over', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班結轉方式')),
                ('overtime_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班事由')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_overtime_author', to='Backend.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('type_of_leave', models.CharField(blank=True, max_length=100, null=True, verbose_name='假別項目')),
                ('start_date_of_leave', models.DateField(blank=True, null=True, verbose_name='請假起始日期')),
                ('end_date_of_leave', models.DateField(blank=True, null=True, verbose_name='請假結束日期')),
                ('start_time_of_leave', models.CharField(blank=True, max_length=100, null=True, verbose_name='請假起始時間')),
                ('end_time_of_leave', models.CharField(blank=True, max_length=100, null=True, verbose_name='請假結束時間')),
                ('leave_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='申請時數')),
                ('substitute', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作代理人')),
                ('leave_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='請假事由')),
                ('backlog', models.CharField(blank=True, max_length=100, null=True, verbose_name='待辦事項')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_author', to='Backend.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '請假',
                'verbose_name_plural': '請假',
            },
        ),
    ]
