# Generated by Django 3.2.20 on 2023-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0095_leave_work_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='internal_content',
            field=models.TextField(blank=True, null=True, verbose_name='紀錄(對內)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='business_assistant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='業務助理'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='business_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='業務電話'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手機'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='專案名稱'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_validity_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='報價單有效期'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='work_item',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='Backend.Work_Item', verbose_name='工項'),
        ),
    ]
