# Generated by Django 3.2.20 on 2023-08-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0096_auto_20230824_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval_targetdepartment',
            name='employee_order',
            field=models.ManyToManyField(to='Backend.Employee', verbose_name='員工簽核順序'),
        ),
    ]
