# Generated by Django 3.2.20 on 2023-08-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0099_leave_param'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_param',
            old_name='backlog',
            new_name='leave_rules',
        ),
        migrations.AddField(
            model_name='leave_param',
            name='control',
            field=models.BooleanField(blank=True, default=False, verbose_name='假控'),
        ),
        migrations.AddField(
            model_name='leave_param',
            name='deduct_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='扣薪 %'),
        ),
        migrations.AddField(
            model_name='leave_param',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=2, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='leave_param',
            name='is_attachment',
            field=models.BooleanField(blank=True, default=False, verbose_name='附件提示'),
        ),
    ]
