# Generated by Django 3.2.20 on 2023-08-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0101_rename_leave_reason_leave_param_is_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_confirmation',
            name='quotation_id',
        ),
        migrations.AddField(
            model_name='project_confirmation',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.quotation', verbose_name='報價單號'),
        ),
    ]
