# Generated by Django 3.2.20 on 2023-08-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0102_auto_20230828_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_confirmation',
            name='project_name',
        ),
    ]
