# Generated by Django 3.2.20 on 2023-08-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0103_remove_project_confirmation_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('工程確認單', '工程確認單'), ('工程派任計畫單', '工程派任計畫單'), ('派工單', '派工單'), ('請假單', '請假單')], max_length=20, verbose_name='表單名稱')),
                ('approval_order', models.JSONField(null=True, verbose_name='員工簽核順序')),
            ],
            options={
                'verbose_name': '簽核流程管理',
                'verbose_name_plural': '簽核流程管理',
            },
        ),
        migrations.RemoveField(
            model_name='approvalmodel',
            name='current_department',
        ),
        migrations.RemoveField(
            model_name='approvalmodel',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='project_confirmation',
            name='client',
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='current_index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='待簽核index'),
        ),
        migrations.DeleteModel(
            name='Approval_TargetDepartment',
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='target_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Backend.approval_target', verbose_name='依附簽核'),
        ),
    ]
