# Generated by Django 3.2.20 on 2023-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0104_auto_20230828_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_param',
            name='gender',
            field=models.CharField(blank=True, choices=[('不限', '不限'), ('男', '男'), ('女', '女')], max_length=5, null=True, verbose_name='性別'),
        ),
    ]
