# Generated by Django 3.2.20 on 2023-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0105_alter_leave_param_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_param',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('特休假', '特休假'), ('補休假', '補休假'), ('一般假', '一般假'), ('特別假', '特別假')], max_length=5, null=True, verbose_name='項目類別'),
        ),
    ]
