# Generated by Django 3.2.20 on 2023-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0106_alter_leave_param_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_param',
            name='control',
            field=models.BooleanField(blank=True, default=True, verbose_name='假控'),
        ),
    ]
