# Generated by Django 3.2.20 on 2023-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0108_alter_leave_type_of_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_param',
            name='minimum_leave_number',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True, verbose_name='最低請假數(為0就不卡控)'),
        ),
        migrations.AlterField(
            model_name='leave_param',
            name='minimum_leave_unit',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True, verbose_name='最小請假單位(為0就不卡控)'),
        ),
    ]
