# Generated by Django 3.2.20 on 2023-08-31 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0111_auto_20230831_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_confirmation_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Employee_Assign_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Job_Assign_Approval', to='Backend.approvalmodel'),
        ),
        migrations.CreateModel(
            name='SysMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('watch', models.BooleanField(default=False, verbose_name='已看過')),
                ('Target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_messages', to='Backend.employee', verbose_name='建立人')),
            ],
            options={
                'verbose_name': '系統消息',
                'verbose_name_plural': '系統消息',
            },
        ),
    ]
