# Generated by Django 3.2.20 on 2023-09-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0112_auto_20230831_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalmodel',
            options={'verbose_name': '簽核執行', 'verbose_name_plural': '簽核執行'},
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_attachment',
            field=models.FileField(blank=True, null=True, upload_to='Invoice', verbose_name='請款單'),
        ),
        migrations.AlterField(
            model_name='sysmessage',
            name='Target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_messages', to='Backend.employee', verbose_name='顯示對象'),
        ),
    ]
