# Generated by Django 3.2.20 on 2023-09-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0113_auto_20230904_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Quotation', to='Backend.client', verbose_name='客戶名稱'),
        ),
    ]
