# Generated by Django 3.2.20 on 2023-09-05 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0114_auto_20230904_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_overtime',
            name='shift_of_overtime',
            field=models.CharField(blank=True, choices=[('1', '班前加班'), ('2', '班後加班')], max_length=1, null=True, verbose_name='班前/班後'),
        ),
        migrations.AlterField(
            model_name='work_overtime',
            name='overtime_reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='加班事由'),
        ),
        migrations.CreateModel(
            name='Work_Overtime_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('date_of_overtime', models.DateField(blank=True, null=True, verbose_name='加班日期')),
                ('shift_of_overtime', models.CharField(blank=True, choices=[('1', '班前加班'), ('2', '班後加班')], max_length=1, null=True, verbose_name='班前/班後')),
                ('type_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班類別')),
                ('start_time_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班起始時間')),
                ('end_time_of_overtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班結束時間')),
                ('overtime_hours', models.IntegerField(blank=True, null=True, verbose_name='申請時數')),
                ('carry_over', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班結轉方式')),
                ('overtime_reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='加班事由')),
                ('Approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work_Overtime_Application_Approval', to='Backend.approvalmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_overtime_application_author', to='Backend.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班',
            },
        ),
    ]
