# Generated by Django 3.2.20 on 2023-09-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0115_auto_20230905_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave',
            new_name='Leave_Application',
        ),
        migrations.AlterModelOptions(
            name='leave_application',
            options={'verbose_name': '請假申請', 'verbose_name_plural': '請假申請'},
        ),
        migrations.AlterModelOptions(
            name='work_overtime_application',
            options={'verbose_name': '加班申請', 'verbose_name_plural': '加班申請'},
        ),
        migrations.DeleteModel(
            name='Work_Overtime',
        ),
    ]
