# Generated by Django 3.2.20 on 2023-09-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0116_auto_20230905_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_application',
            name='end_time_of_leave',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='start_time_of_leave',
        ),
        migrations.RemoveField(
            model_name='work_overtime_application',
            name='end_time_of_overtime',
        ),
        migrations.RemoveField(
            model_name='work_overtime_application',
            name='start_time_of_overtime',
        ),
        migrations.AddField(
            model_name='leave_application',
            name='end_hours_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假結束小時'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='end_mins_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假結束分鐘'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='leave_mins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(分)'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='start_hours_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假起始小時'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='start_mins_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假起始分鐘'),
        ),
        migrations.AddField(
            model_name='work_overtime_application',
            name='end_hours_of_overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='加班結束小時'),
        ),
        migrations.AddField(
            model_name='work_overtime_application',
            name='end_mins_of_overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='加班結束分鐘'),
        ),
        migrations.AddField(
            model_name='work_overtime_application',
            name='overtime_mins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(分)'),
        ),
        migrations.AddField(
            model_name='work_overtime_application',
            name='start_hours_of_overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='加班起始小時'),
        ),
        migrations.AddField(
            model_name='work_overtime_application',
            name='start_mins_of_overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='加班起始分鐘'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(時)'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_application_substitute', to='Backend.employee', verbose_name='工作代理人'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='overtime_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(時)'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='type_of_overtime',
            field=models.CharField(blank=True, choices=[('1', '平日加班')], max_length=1, null=True, verbose_name='加班類別'),
        ),
    ]
