# Generated by Django 3.2.20 on 2023-09-05 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0117_auto_20230905_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Leave_Application_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_reason',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='請假事由'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='overtime_reason',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='加班事由'),
        ),
        migrations.CreateModel(
            name='Clock_Correction_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('date_of_clock', models.DateField(blank=True, null=True, verbose_name='補卡日期')),
                ('shift_of_clock', models.CharField(blank=True, choices=[('1', 'A班')], max_length=1, null=True, verbose_name='補卡班別')),
                ('category_of_clock', models.CharField(blank=True, choices=[('1', '忘打卡'), ('2', '其他')], max_length=1, null=True, verbose_name='補卡類別')),
                ('type_of_clock', models.CharField(blank=True, choices=[('1', '補上班'), ('2', '補下班')], max_length=1, null=True, verbose_name='補卡方式')),
                ('end_hours_of_clock', models.IntegerField(blank=True, default=0, null=True, verbose_name='補卡小時')),
                ('end_mins_of_clock', models.IntegerField(blank=True, default=0, null=True, verbose_name='補卡分鐘')),
                ('clock_reason', models.TextField(blank=True, max_length=300, null=True, verbose_name='補卡事由')),
                ('Approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Clock_Correction_Application_Approval', to='Backend.approvalmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_correction_application_author', to='Backend.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '補卡申請',
                'verbose_name_plural': '補卡申請',
            },
        ),
    ]
