# Generated by Django 3.2.20 on 2023-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0118_auto_20230905_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('system_amount', models.PositiveIntegerField(default=0, verbose_name='系統金額')),
                ('adjustment_amount', models.PositiveIntegerField(default=0, verbose_name='調整金額')),
                ('deduction', models.BooleanField(default=False, verbose_name='扣款項目')),
            ],
        ),
    ]
