# Generated by Django 3.2.20 on 2023-09-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0121_employee_set_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='set_salary',
        ),
    ]
