# Generated by Django 3.2.20 on 2023-09-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0122_remove_employee_set_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_salary',
            field=models.IntegerField(blank=True, default=27000, null=True, verbose_name='薪資'),
        ),
    ]
