# Generated by Django 3.2.20 on 2023-09-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0123_employee_default_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary_details',
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.salarydetail', verbose_name='依附薪資單'),
        ),
    ]
