# Generated by Django 3.2.20 on 2023-09-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0124_auto_20230905_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.salary', verbose_name='依附薪資單'),
        ),
    ]
