# Generated by Django 3.2.20 on 2023-09-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0126_alter_salarydetail_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
    ]
