# Generated by Django 3.2.20 on 2023-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0127_alter_quotation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='end_hours_of_leave',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='請假結束小時'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='end_mins_of_leave',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='請假結束分鐘'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_hours',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='申請時數(時)'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_mins',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='申請時數(分)'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='start_hours_of_leave',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='請假起始小時'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='start_mins_of_leave',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='請假起始分鐘'),
        ),
    ]
