# Generated by Django 3.2.20 on 2023-09-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0128_auto_20230906_1411'),
        ('Backend', '0128_auto_20230906_1602'),
    ]

    operations = [
    ]
