# Generated by Django 3.2.20 on 2023-09-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0129_merge_0128_auto_20230906_1411_0128_auto_20230906_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='end_hours_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假結束小時'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='end_mins_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假結束分鐘'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(時)'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_mins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='申請時數(分)'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='start_hours_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假起始小時'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='start_mins_of_leave',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='請假起始分鐘'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='carry_over',
            field=models.CharField(blank=True, choices=[('1', '加班費')], max_length=100, null=True, verbose_name='加班結轉方式'),
        ),
    ]
