# Generated by Django 3.2.20 on 2023-09-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0130_auto_20230907_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='type_of_clock',
            field=models.CharField(blank=True, choices=[('1', '正常打卡'), ('2', '補打卡')], default='1', max_length=1, null=True, verbose_name='打卡類別'),
        ),
        migrations.AddField(
            model_name='clock_correction_application',
            name='clock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_correction_application', to='Backend.clock'),
        ),
        migrations.AlterField(
            model_name='approval_target',
            name='name',
            field=models.CharField(choices=[('Project_Employee_Assign', '派工單'), ('Leave_Application', '請假單'), ('Work_Overtime_Application', '補卡單'), ('Clock_Correction_Application', '加班單')], max_length=30, verbose_name='表單名稱'),
        ),
    ]
