# Generated by Django 3.2.20 on 2023-09-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0131_auto_20230911_1648'),
        ('Backend', '0131_auto_20230911_1739'),
    ]

    operations = [
    ]
