# Generated by Django 3.2.20 on 2023-09-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0132_merge_0131_auto_20230911_1648_0131_auto_20230911_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarydetail',
            options={'verbose_name': '薪資明細', 'verbose_name_plural': '薪資明細'},
        ),
    ]
