# Generated by Django 3.2.20 on 2023-09-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0133_alter_salarydetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='type_of_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lication', to='Backend.leave_param', verbose_name='假別項目'),
        ),
    ]
