# Generated by Django 3.2.20 on 2023-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0134_alter_leave_application_type_of_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='construction_location',
        ),
        migrations.AlterField(
            model_name='leave_param',
            name='leave_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='給假數(小時)'),
        ),
    ]
