# Generated by Django 3.2.20 on 2023-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0135_auto_20230912_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Leave_Application_attachment', verbose_name='請假附件'),
        ),
    ]
