# Generated by Django 3.2.20 on 2023-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0136_leave_application_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_correction_application',
            name='category_of_clock',
            field=models.CharField(choices=[('1', '忘打卡'), ('2', '其他')], default='1', max_length=1, verbose_name='補卡類別'),
        ),
        migrations.AlterField(
            model_name='clock_correction_application',
            name='shift_of_clock',
            field=models.CharField(choices=[('1', 'A班')], default='1', max_length=1, verbose_name='補卡班別'),
        ),
        migrations.AlterField(
            model_name='clock_correction_application',
            name='type_of_clock',
            field=models.CharField(choices=[('1', '補上班'), ('2', '補下班')], default='1', max_length=1, verbose_name='補卡方式'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='location',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東')], max_length=4, null=True, verbose_name='工作地點'),
        ),
    ]
