# Generated by Django 3.2.20 on 2023-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0137_auto_20230913_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_overtime_application',
            name='carry_over',
            field=models.CharField(choices=[('1', '加班費')], default='1', max_length=100, verbose_name='加班結轉方式'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='shift_of_overtime',
            field=models.CharField(choices=[('1', '班前加班'), ('2', '班後加班')], default='1', max_length=1, verbose_name='班前/班後'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='type_of_overtime',
            field=models.CharField(choices=[('1', '平日加班')], default='1', max_length=1, verbose_name='加班類別'),
        ),
    ]
