# Generated by Django 3.2.20 on 2023-09-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0138_auto_20230913_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_list', to='Backend.employee', verbose_name='申請者'),
        ),
        migrations.AlterField(
            model_name='leave_param',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_param_author', to='Backend.employee', verbose_name='申請人'),
        ),
    ]
