# Generated by Django 3.2.20 on 2023-09-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0140_clock_clock_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clock',
            options={'ordering': ['clock_date', 'clock_time'], 'verbose_name': '打卡紀錄', 'verbose_name_plural': '打卡紀錄'},
        ),
        migrations.AlterField(
            model_name='referencetable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='錢/單位'),
        ),
    ]
