# Generated by Django 3.2.20 on 2023-09-15 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0141_auto_20230914_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clock',
            options={'ordering': ['clock_date', 'clock_time'], 'verbose_name': '打卡紀錄', 'verbose_name_plural': '打卡紀錄'},
        ),
        migrations.AlterField(
            model_name='clock',
            name='clock_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='打卡時間'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clock_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='requisition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請購單位'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='location',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東')], max_length=4, null=True, verbose_name='工作地點'),
        ),
    ]
