# Generated by Django 3.2.20 on 2023-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0141_auto_20230915_1203'),
        ('Backend', '0143_auto_20230915_1225'),
    ]

    operations = [
    ]
