# Generated by Django 3.2.20 on 2023-09-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0144_merge_0141_auto_20230915_1203_0143_auto_20230915_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_job_assign',
            name='work_method',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='工作方式(T派工、F文書)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location_city',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, null=True, verbose_name='居住城市(用於計算津貼)'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='location',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, null=True, verbose_name='工作地點'),
        ),
        migrations.AlterField(
            model_name='referencetable',
            name='location_city_business_trip',
            field=models.CharField(choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, verbose_name='出差地'),
        ),
        migrations.AlterField(
            model_name='referencetable',
            name='location_city_residence',
            field=models.CharField(choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, verbose_name='居住地'),
        ),
    ]
