# Generated by Django 3.2.20 on 2023-09-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0145_auto_20230915_1548'),
        ('Backend', '0146_auto_20230915_1556'),
    ]

    operations = [
    ]
