# Generated by Django 3.2.20 on 2023-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0147_merge_0145_auto_20230915_1548_0146_auto_20230915_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location_city',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, null=True, verbose_name='居住城市(用於計算)'),
        ),
    ]
