# Generated by Django 3.2.20 on 2023-09-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0148_alter_employee_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_confirmation',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.requisition', verbose_name='請購單位'),
        ),
    ]
