# Generated by Django 3.2.20 on 2023-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0150_auto_20230915_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clock_GPS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clock_time',
            field=models.TimeField(blank=True, null=True, verbose_name='打卡時間'),
        ),
    ]
