# Generated by Django 3.2.20 on 2023-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0151_auto_20230916_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_job_assign',
            name='location',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=4, null=True, verbose_name='工作地點'),
        ),
    ]
