# Generated by Django 3.2.20 on 2023-09-19 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0153_auto_20230919_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_created', to='Backend.employee', verbose_name='建立人'),
        ),
    ]
