# Generated by Django 3.2.20 on 2023-09-19 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0155_auto_20230919_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel_application',
            options={'ordering': ['-id'], 'verbose_name': '車程申請', 'verbose_name_plural': '車程申請'},
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_overtime_application_author', to='Backend.employee', verbose_name='申請人'),
        ),
        migrations.CreateModel(
            name='ExtraWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('date', models.DateField(verbose_name='日期')),
                ('date_type', models.CharField(choices=[('extra_work', '額外上班日(補班日)'), ('day_off', '平日休假日')], max_length=10, verbose_name='日期類型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExtraWorkDay_author', to='Backend.employee', verbose_name='建立人')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
