# Generated by Django 3.2.20 on 2023-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0156_auto_20230919_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraworkday',
            name='date_type',
            field=models.CharField(choices=[('extra_work', '補班、額外上班日(這天要上班)'), ('day_off', '平日休假日(這天不用上班)')], max_length=10, verbose_name='日期類型'),
        ),
    ]
