# Generated by Django 3.2.20 on 2023-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0160_auto_20230925_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_application',
            name='location_city_business_trip',
        ),
    ]
