# Generated by Django 3.2.20 on 2023-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0161_remove_travel_application_location_city_business_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_application',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='申請日期'),
        ),
    ]
