# Generated by Django 3.2.20 on 2023-09-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0162_travel_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_application',
            name='date',
        ),
    ]
