# Generated by Django 3.2.20 on 2023-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0163_remove_travel_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_application',
            name='job_assign',
        ),
        migrations.AddField(
            model_name='travel_application',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='申請日期'),
        ),
        migrations.AddField(
            model_name='travel_application',
            name='location_city_end',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], default='', max_length=4, null=True, verbose_name='到達'),
        ),
        migrations.AddField(
            model_name='travel_application',
            name='location_city_go',
            field=models.CharField(blank=True, choices=[('台東', '台東'), ('花蓮', '花蓮'), ('宜蘭', '宜蘭'), ('北北基', '北北基'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('南投', '南投'), ('彰化', '彰化'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('花蓮', '花蓮'), ('台東', '台東')], default='', max_length=4, null=True, verbose_name='出發地'),
        ),
        migrations.AlterField(
            model_name='approval_target',
            name='name',
            field=models.CharField(choices=[('Project_Employee_Assign', '派工單'), ('Leave_Application', '請假單'), ('Work_Overtime_Application', '加班單'), ('Clock_Correction_Application', '補卡單'), ('Travel_Application', '車程津貼單')], max_length=30, verbose_name='表單名稱'),
        ),
    ]
