# Generated by Django 3.2.20 on 2023-09-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0164_auto_20230930_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_application',
            old_name='approval_date',
            new_name='date',
        ),
    ]
