# Generated by Django 3.2.20 on 2023-10-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0165_rename_approval_date_travel_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='order',
            field=models.JSONField(null=True, verbose_name='員工簽核順序'),
        ),
    ]
