# Generated by Django 3.2.20 on 2023-10-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0166_approvalmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_correction_application',
            name='clock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_correction', to='Backend.clock'),
        ),
    ]
