# Generated by Django 3.2.20 on 2023-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0167_alter_clock_correction_application_clock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='start_date',
            new_name='start_work_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='certificates_addition',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='證照加給'),
        ),
        migrations.AddField(
            model_name='employee',
            name='food_addition',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='伙食津貼'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_insurance',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='健保'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_addition',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='職務加給'),
        ),
        migrations.AddField(
            model_name='employee',
            name='labor_pension',
            field=models.PositiveIntegerField(blank=True, default=6, null=True, verbose_name='勞退比例(%)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='labor_protection',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='勞保'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_addition',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='手機加給'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='default_salary',
            field=models.PositiveIntegerField(blank=True, default=27000, null=True, verbose_name='基本薪資'),
        ),
    ]
