# Generated by Django 3.2.20 on 2023-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0168_auto_20231002_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='報價單編號'),
        ),
    ]
