# Generated by Django 3.2.20 on 2023-10-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0169_quotation_quotation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_employee_assign',
            name='remark',
            field=models.TextField(blank=True, null='', verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='test_description',
            field=models.TextField(blank=True, null='', verbose_name='檢查項目描述'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='test_items',
            field=models.TextField(blank=True, null='', verbose_name='檢查項目'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clock_in_or_out',
            field=models.BooleanField(verbose_name='勾起來上班，沒勾下班'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='certificates_addition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='證照加給'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='default_salary',
            field=models.PositiveIntegerField(blank=True, default=26000, null=True, verbose_name='基本薪資'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='food_addition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='伙食津貼'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_insurance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='健保'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_addition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='職務加給'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='labor_protection',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='勞保'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_addition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='手機加給'),
        ),
    ]
