# Generated by Django 3.2.20 on 2023-10-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0170_auto_20231003_2027'),
        ('Backend', '0170_auto_20231003_2102'),
    ]

    operations = [
    ]
