# Generated by Django 3.2.20 on 2023-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0172_auto_20231004_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='tax_deduction',
            field=models.BooleanField(default=False, verbose_name='應稅項目'),
        ),
    ]
