# Generated by Django 3.2.20 on 2023-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0174_remove_employee_food_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='seniority',
        ),
        migrations.AddField(
            model_name='work_item',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='current_status',
            field=models.CharField(choices=[('completed', '完成'), ('in_process', '進行中'), ('rejected', '駁回')], default='in_process', max_length=30),
        ),
        migrations.AlterField(
            model_name='work_item',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='數量'),
        ),
    ]
