# Generated by Django 3.2.20 on 2023-10-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0176_salarydetail_five'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='five',
            field=models.BooleanField(default=False, verbose_name='第一次發薪'),
        ),
    ]
