# Generated by Django 3.2.20 on 2023-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0177_alter_salarydetail_five'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborHealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_low', models.IntegerField(verbose_name='薪資(低)')),
                ('salary_high', models.IntegerField(verbose_name='薪資(高)')),
                ('labor_insurance_personal', models.IntegerField(verbose_name='勞保個人自付')),
                ('labor_insurance_employer', models.IntegerField(verbose_name='勞保單位負擔')),
                ('health_insurance_personal', models.IntegerField(verbose_name='健保個人自付')),
                ('health_insurance_employer', models.IntegerField(verbose_name='健保單位負擔')),
                ('retirement_benefit', models.IntegerField(verbose_name='勞退公提')),
            ],
            options={
                'verbose_name': '勞健保參照',
                'verbose_name_plural': '勞健保參照',
            },
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='five',
            field=models.BooleanField(default=False, verbose_name='薪資單發放'),
        ),
    ]
