# Generated by Django 3.2.20 on 2023-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0181_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='test_items',
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='test_items',
            field=models.ManyToManyField(blank=True, related_name='employee_assign_test_items', to='Backend.Examination', verbose_name='檢查項目'),
        ),
    ]
