# Generated by Django 3.2.20 on 2023-10-09 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0182_auto_20231009_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('test_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='檢查項目')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'verbose_name': '檢查項目',
                'verbose_name_plural': '檢查項目',
            },
        ),
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='test_items',
            field=models.ManyToManyField(blank=True, related_name='employee_assign_test_items', to='Backend.Test_Items', verbose_name='檢查項目'),
        ),
    ]
