# Generated by Django 3.2.20 on 2023-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0183_auto_20231009_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='test_description',
        ),
        migrations.AddField(
            model_name='test_items',
            name='format_and_voltage',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='廠牌規格/額定電壓'),
        ),
        migrations.AddField(
            model_name='test_items',
            name='level',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='加壓等級'),
        ),
        migrations.AddField(
            model_name='test_items',
            name='number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='數量'),
        ),
        migrations.AddField(
            model_name='test_items',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='檢驗日期'),
        ),
        migrations.AddField(
            model_name='test_items',
            name='test_location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='試驗地點'),
        ),
        migrations.AlterField(
            model_name='test_items',
            name='test_item',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='檢查項目'),
        ),
    ]
