# Generated by Django 3.2.20 on 2023-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0185_auto_20231009_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_items_description',
            name='number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='test_items',
            field=models.ManyToManyField(blank=True, related_name='employee_assign_test_items', to='Backend.Test_Items_Description', verbose_name='檢查項目'),
        ),
        migrations.AlterField(
            model_name='test_items_description',
            name='test_items',
            field=models.ManyToManyField(blank=True, to='Backend.Test_Items', verbose_name='檢查項目'),
        ),
    ]
