# Generated by Django 3.2.20 on 2023-10-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0186_auto_20231009_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_items_description',
            name='test_items',
        ),
        migrations.AddField(
            model_name='test_items_description',
            name='test_items',
            field=models.CharField(blank=True, max_length=300, verbose_name='檢查項目'),
        ),
    ]
