# Generated by Django 3.2.20 on 2023-10-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0187_auto_20231009_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Items',
        ),
    ]
