# Generated by Django 3.2.20 on 2023-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0188_delete_test_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='test_items',
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='test_items_str',
            field=models.TextField(blank=True, verbose_name='檢查項目字串'),
        ),
        migrations.DeleteModel(
            name='Test_Items_Description',
        ),
    ]
