# Generated by Django 3.2.20 on 2023-10-10 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0189_auto_20231009_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_item',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='work_item',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='單價'),
        ),
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('days', models.IntegerField(default=0, verbose_name='天數')),
                ('end_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='截止日期')),
                ('remark', models.DateField(blank=True, null=True, verbose_name='備註')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='annualleaves',
            field=models.ManyToManyField(blank=True, related_name='AnnualLeave_user', to='Backend.AnnualLeave'),
        ),
    ]
