# Generated by Django 3.2.20 on 2023-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0190_auto_20231010_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualleave',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='annualleave',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
