# Generated by Django 3.2.20 on 2023-10-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0191_auto_20231010_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, related_name='quotationfile', to='Backend.UploadedFile'),
        ),
    ]
