# Generated by Django 3.2.20 on 2023-10-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0192_quotation_uploaded_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quote_date',
            field=models.DateField(blank=True, null=True, verbose_name='報價日期'),
        ),
    ]
