# Generated by Django 3.2.20 on 2023-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0194_remove_quotation_invoice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='UploadedFile/'),
        ),
    ]
