# Generated by Django 3.2.20 on 2023-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0195_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='lead_employee',
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='lead_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_lead_employee', to='Backend.Employee', verbose_name='帶班主管'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='work_employee',
            field=models.ManyToManyField(blank=True, related_name='projects_work_employee', to='Backend.Employee', verbose_name='檢測人員'),
        ),
    ]
