# Generated by Django 3.2.20 on 2023-10-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0197_auto_20231013_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quotation_buy', to='Backend.client', verbose_name='請購單位'),
        ),
    ]
