# Generated by Django 3.2.20 on 2023-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0198_quotation_requisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tel',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件'),
        ),
        migrations.AddField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真'),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AddField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
    ]
