# Generated by Django 3.2.20 on 2023-10-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0199_auto_20231013_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='work_item',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='work_item',
            name='contract_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合約編號'),
        ),
        migrations.AddField(
            model_name='work_item',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_item_requisition', to='Backend.client', verbose_name='業主單位'),
        ),
        migrations.AddField(
            model_name='work_item',
            name='year_money',
            field=models.TextField(blank=True, null=True, verbose_name='年度單價'),
        ),
        migrations.AlterField(
            model_name='work_item',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工項編號'),
        ),
        migrations.AlterField(
            model_name='work_item',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工項名稱(試驗項目)'),
        ),
    ]
