# Generated by Django 3.2.20 on 2023-10-14 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0200_auto_20231014_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Item_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='數量')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work_Item_Number', to='Backend.work_item', verbose_name='工項名稱')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
