# Generated by Django 3.2.20 on 2023-10-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0201_work_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_item_number',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Quotation_Work_Item_Number', to='Backend.quotation', verbose_name='報價單'),
        ),
    ]
