# Generated by Django 3.2.20 on 2023-10-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0207_auto_20231015_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='work_item',
        ),
    ]
