# Generated by Django 3.2.20 on 2023-10-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0208_remove_quotation_work_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_item_number',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quotation_Work_Item_Number', to='Backend.quotation', verbose_name='報價單'),
        ),
        migrations.AlterField(
            model_name='work_item_number',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Work_Item_Number', to='Backend.work_item', verbose_name='工項名稱'),
        ),
    ]
