# Generated by Django 3.2.20 on 2023-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0210_auto_20231016_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualleave',
            options={'verbose_name': '特休紀錄表', 'verbose_name_plural': '特休紀錄表'},
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='work_method',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='工作方式(是:派工、否:非派工)'),
        ),
    ]
