# Generated by Django 3.2.20 on 2023-10-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0212_auto_20231018_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_correction_application',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Clock_Correction_Application_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Leave_Application_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_confirmation_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_confirmation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Confirmation_author', to='Backend.employee', verbose_name='建立人'),
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Employee_Assign_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='project_job_assign',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Job_Assign_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Salary_author', to='Backend.employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_user', to='Backend.employee', verbose_name='員工'),
        ),
        migrations.AlterField(
            model_name='travel_application',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Travel_Application_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='Approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work_Overtime_Application_Approval', to='Backend.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='work_overtime_application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_overtime_application_author', to='Backend.employee', verbose_name='申請人'),
        ),
    ]
