# Generated by Django 3.2.20 on 2023-10-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0214_project_employee_assign_carry_equipments_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='carry_equipments',
        ),
    ]
