# Generated by Django 3.2.20 on 2023-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0215_remove_project_employee_assign_carry_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_employee_assign',
            name='remark_two',
            field=models.TextField(blank=True, null='', verbose_name='異常報告及聯絡事項'),
        ),
        migrations.AddField(
            model_name='project_employee_assign',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, related_name='employy_assign_files', to='Backend.UploadedFile'),
        ),
    ]
