# Generated by Django 3.2.20 on 2023-10-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0216_auto_20231019_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee_assign',
            name='remark_two',
        ),
        migrations.AlterField(
            model_name='project_employee_assign',
            name='remark',
            field=models.TextField(blank=True, null='', verbose_name='異常報告及聯絡事項'),
        ),
    ]
