# Generated by Django 3.2.20 on 2023-10-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0217_auto_20231020_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='business_assistant',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='business_tel',
        ),
        migrations.AddField(
            model_name='quotation',
            name='business_assistant_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotaion_process', to='Backend.employee', verbose_name='業務助理'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Quotation_buy', to='Backend.client', verbose_name='請購單位'),
        ),
    ]
