# Generated by Django 3.2.20 on 2023-10-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0218_auto_20231020_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='last_excel',
            field=models.FileField(blank=True, null=True, upload_to='last_file', verbose_name='最終版報價單'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話(報價單顯示)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='個人E_Mail(報價單顯示)'),
        ),
    ]
