# Generated by Django 3.2.20 on 2023-10-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0219_auto_20231020_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_employee_assign',
            name='last_excel',
            field=models.FileField(blank=True, null=True, upload_to='last_file', verbose_name='最終版報價單'),
        ),
    ]
