# Generated by Django 3.2.20 on 2023-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0220_project_employee_assign_last_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客戶編號'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_principal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司負責人'),
        ),
    ]
