# Generated by Django 3.2.20 on 2023-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0221_auto_20231021_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_english_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='客戶英文名稱'),
        ),
        migrations.AddField(
            model_name='client',
            name='established',
            field=models.DateField(blank=True, null=True, verbose_name='成立時間'),
        ),
        migrations.AddField(
            model_name='client',
            name='pay_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='付款天數'),
        ),
        migrations.AddField(
            model_name='client',
            name='pay_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='client',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司地址'),
        ),
    ]
