# Generated by Django 3.2.20 on 2023-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0222_auto_20231021_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '客戶管理', 'verbose_name_plural': '客戶管理'},
        ),
        migrations.AddField(
            model_name='client',
            name='address_str',
            field=models.TextField(blank=True, null=True, verbose_name='地址字串'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_str',
            field=models.TextField(blank=True, null=True, verbose_name='聯絡人字串'),
        ),
    ]
