# Generated by Django 3.2.20 on 2023-10-22 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0223_auto_20231021_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miss_Food_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('date', models.DateField(blank=True, null=True, verbose_name='申請日期')),
                ('Approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Food_Application_Approval', to='Backend.approvalmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Miss_Food_author', to='Backend.employee', verbose_name='建立人')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.employee')),
                ('project_job_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employee_assign_food', to='Backend.project_job_assign', verbose_name='工作派任計畫')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
