# Generated by Django 3.2.20 on 2023-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0230_auto_20231122_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='last_excel',
        ),
        migrations.AddField(
            model_name='quotation',
            name='last_excel',
            field=models.ManyToManyField(blank=True, related_name='quotationLastExcelFile', to='Backend.UploadedFile', verbose_name='最終版報價單'),
        ),
    ]
