# Generated by Django 3.2.20 on 2023-11-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0231_auto_20231127_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_chinese_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客戶中文名稱'),
        ),
    ]
