# Generated by Django 3.2.20 on 2023-12-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0232_client_client_chinese_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_param',
            old_name='hours',
            new_name='leave_quantity',
        ),
    ]
