# Generated by Django 3.2.20 on 2024-01-27 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0233_rename_hours_leave_param_leave_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('1', '(1)付款方式:完工請款100%.初次交易,請配合開立即期票或匯款。'), ('2', '(2)付款方式:完工請款100%.發票開立後期票30天。'), ('3', '(3)付款方式:與業主額外議定(此部分開放自行填寫,利配合部分廠商付款特殊要求)')], max_length=1, null=True, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, related_name='quotationfile', to='Backend.UploadedFile', verbose_name='內部記錄檔案'),
        ),
    ]
