# Generated by Django 4.0.1 on 2023-05-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
